import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import StoreProvider from "@/app/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: {
		template: '%s | Admin Template',
		default: 'Admin Template',
	},
  	description: 'Generated by Jayanta Biswas',
  	metadataBase: new URL('https://jayanta.me'),
};

export default function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<StoreProvider>{children}</StoreProvider>
				<Toaster />
			</body>
		</html>
	);
}
